# Generated by Django 2.2.2 on 2020-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200604_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='srnamw',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
