# Generated by Django 2.2.2 on 2020-06-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_person_srnamw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='srnamw',
            field=models.SlugField(unique=True),
        ),
    ]
