# Generated by Django 2.2.2 on 2020-06-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200604_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='srnamw',
        ),
        migrations.AddField(
            model_name='person',
            name='whtsapp',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='youtube',
            field=models.URLField(default=''),
        ),
    ]
