# Generated by Django 2.2.2 on 2020-06-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200604_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='youtube',
            new_name='joininglink',
        ),
        migrations.AddField(
            model_name='person',
            name='img1',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='img10',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='img2',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='img3',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='img4',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='img5',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='img6',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='img7',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='img8',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='img9',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='pic',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='person',
            name='youtube1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='youtube2',
            field=models.URLField(default=''),
        ),
    ]
