# Generated by Django 2.2.2 on 2020-06-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200604_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='chittaranjan.ghoshal@gmail.com', max_length=500),
        ),
    ]
