# Generated by Django 2.2.2 on 2020-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_person_xx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='xx',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='chittaranjan.ghoshal@gmail.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.FloatField(default='0000000000', max_length=10),
        ),
    ]
