# Generated by Django 2.2.2 on 2020-06-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200605_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='joininglink',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='whtsapp',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='youtube1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='youtube2',
            field=models.URLField(blank=True, default=''),
        ),
    ]
