# Generated by Django 2.2.2 on 2020-06-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200608_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='youtube3',
            field=models.URLField(blank=True, default=''),
        ),
    ]
