# Generated by Django 2.2.2 on 2020-06-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_person_youtube3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
