# Generated by Django 3.0.7 on 2020-06-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200610_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='whtsapp',
            field=models.URLField(blank=True, choices=[('https://chat.whatsapp.com/HpNnslElleO1DDvY8b4OHr', 'impact_patna'), ('https://chat.whatsapp.com/C3UuGHhhJj5KtxpwkdFElz', 'GaumataGroup'), ('https://chat.whatsapp.com/K3z9zjoBL9N0bvopL7hmzH', 'Impact_Original'), ('https://chat.whatsapp.com/ELTkQ1xDk5GKEcw3GLDxbl', 'Impact_Banswara'), ('https://chat.whatsapp.com/KKZkCJNCqH1G9IjlQTJr8S', 'Impact_Uttarakhand'), ('https://chat.whatsapp.com/DirSyjkmK1DHNjVQYjZ0sK', 'fivet_in_3 months'), ('https://chat.whatsapp.com/HcRTw8JMASB760KlhVkRP2', 'Impact_Mumbai'), ('https://chat.whatsapp.com/HiD9k4slVPV2Q0FlGrbfMW', 'IMPACT_DESK_2'), ('https://chat.whatsapp.com/Ebm33ZFOL1T33BxtMXmQwj', 'IMPACT_DESK'), ('https://chat.whatsapp.com/KvP27ZjMvDpB88xCMNm2pX', 'IMPACT_TIGER_TEAM')], default=''),
        ),
    ]
